const $=(selector)=>document.querySelector(selector);
const $$=(selector)=>[...document.querySelectorAll(selector)];
const defaults={timeline:0,timelineSeen:[],slides:0,classifier:0,environments:0,agentTypes:0,memory:0,peas:0,quiz:0};
const state={...defaults,...JSON.parse(localStorage.getItem('si_u1')||'{}')};
function save(){localStorage.setItem('si_u1',JSON.stringify(state));updateProgress()}
function updateProgress(){const keys=['timeline','slides','classifier','environments','agentTypes','memory','peas','quiz'];const value=Math.round(keys.reduce((sum,key)=>sum+(state[key]||0),0)/keys.length);$('#progressBar').style.width=value+'%';$('#progressText').textContent=value+' %'}
function show(id){$$('.panel').forEach(panel=>panel.classList.toggle('active',panel.id===id));$$('.nav button').forEach(button=>button.classList.toggle('active',button.dataset.target===id));const panel=$('#'+id);if(panel){panel.focus();history.replaceState(null,'','#'+id)}}
$$('.nav button').forEach(button=>button.addEventListener('click',()=>show(button.dataset.target)));
$$('.next').forEach(button=>button.addEventListener('click',()=>show(button.dataset.next)));

const timeline=[
  {year:'1950',title:'Turing cambia la pregunta',body:'Alan Turing propone el “juego de imitación” como una forma operacional de discutir la conducta inteligente de una máquina.',meaning:'La discusión se desplaza de una definición abstracta de pensar hacia evidencia observable y criterios de prueba.',source:'https://academic.oup.com/mind/article/LIX/236/433/986238'},
  {year:'1955–1956',title:'La IA se nombra como campo',body:'McCarthy, Minsky, Rochester y Shannon proponen el proyecto de verano de Dartmouth, realizado en 1956.',meaning:'La propuesta reúne lenguaje, abstracción, aprendizaje y redes neuronales bajo un programa de investigación común.',source:'https://jmc.stanford.edu/articles/dartmouth/dartmouth.pdf'},
  {year:'1960s–1980s',title:'Reglas, búsqueda y conocimiento',body:'Gran parte del trabajo se concentra en representar conocimiento explícito, buscar soluciones y construir sistemas expertos.',meaning:'Las reglas siguen siendo valiosas cuando la lógica debe ser visible y trazable; no son una etapa “obsoleta”.',source:'https://artint.info/3e/html/ArtInt3e.html'},
  {year:'1997',title:'Deep Blue vence a Kasparov',body:'El sistema de IBM combina búsqueda paralela, función de evaluación y una base de partidas para jugar ajedrez al máximo nivel.',meaning:'Un logro impresionante en una tarea delimitada no equivale a inteligencia general.',source:'https://research.ibm.com/publications/deep-blue'},
  {year:'2010s',title:'El aprendizaje profundo gana escala',body:'Más datos, cómputo y redes profundas impulsan avances en percepción, lenguaje y predicción.',meaning:'El comportamiento se aprende a partir de ejemplos; por ello importan los datos, la generalización y el sesgo.',source:'https://artint.info/3e/html/ArtInt3e.html'},
  {year:'2016',title:'AlphaGo combina aprendizaje y búsqueda',body:'AlphaGo integra redes neuronales con algoritmos avanzados de búsqueda para seleccionar y evaluar movimientos.',meaning:'Los sistemas potentes suelen ser híbridos: combinan mecanismos en lugar de depender de una sola técnica.',source:'https://deepmind.google/research/alphago/'},
  {year:'2017',title:'El transformer reorganiza el lenguaje',body:'Vaswani y colaboradores presentan una arquitectura basada en mecanismos de atención, sin recurrencia ni convoluciones en el núcleo.',meaning:'La arquitectura habilita procesamiento paralelo y se vuelve una base central de modelos generativos posteriores.',source:'https://arxiv.org/abs/1706.03762'},
  {year:'2022–actualidad',title:'La IA generativa llega al uso cotidiano',body:'Las interfaces conversacionales amplían el acceso a modelos capaces de generar texto y otros contenidos.',meaning:'La fluidez no garantiza verdad ni pertinencia: deben añadirse fuentes, pruebas, límites, seguridad y supervisión.',source:'https://openai.com/index/chatgpt/'}
];
let timelineIndex=0;
function renderTimeline(){
  $('#timelineList').innerHTML=timeline.map((item,index)=>`<button role="listitem" data-index="${index}" class="${index===timelineIndex?'active':''}">${item.year} · ${item.title}</button>`).join('');
  const item=timeline[timelineIndex];$('#timelineDetail').innerHTML=`<p class="year">${item.year} · Hito ${timelineIndex+1}/${timeline.length}</p><h3>${item.title}</h3><p>${item.body}</p><p class="meaning"><strong>¿Por qué importa?</strong><br>${item.meaning}</p><p><a href="${item.source}" target="_blank" rel="noreferrer" style="color:#a8e5e7">Abrir fuente primaria o académica ↗</a></p>`;
  if(!state.timelineSeen.includes(timelineIndex))state.timelineSeen.push(timelineIndex);state.timeline=Math.round(state.timelineSeen.length/timeline.length*100);save();
  $$('#timelineList button').forEach(button=>button.addEventListener('click',()=>{timelineIndex=Number(button.dataset.index);renderTimeline()}));
}
renderTimeline();

const slides=[
  {k:'Punto de partida',t:'No todo lo automático es inteligente',b:'Una automatización ejecuta reglas o secuencias previstas. Puede ser útil y compleja sin aprender ni inferir.',e:'Ejemplo: una lámpara que se enciende a las 19:00 por temporizador.'},
  {k:'Definición funcional',t:'Un sistema de IA infiere cómo producir salidas',b:'Recibe entradas y genera predicciones, contenido, recomendaciones o decisiones orientadas a objetivos.',e:'La autonomía y la capacidad de adaptación pueden variar entre sistemas.'},
  {k:'Componente',t:'Un modelo transforma entradas en salidas',b:'Puede clasificar, estimar o generar. Por sí solo no incluye usuarios, interfaz, políticas ni supervisión.',e:'Ejemplo: un modelo asigna una probabilidad de abandono escolar.'},
  {k:'Conjunto',t:'Un sistema integra datos, decisión y acción',b:'Combina modelos o reglas con interfaces, controles y retroalimentación para operar en un contexto.',e:'Ejemplo: recibe señales, estima riesgo, aplica una política y solicita revisión.'},
  {k:'Uso real',t:'Un producto con IA incluye personas y operación',b:'Además del sistema, considera experiencia, soporte, responsabilidades, seguridad y ciclo de vida.',e:'Una aplicación atractiva puede contener un sistema deficiente.'},
  {k:'Cuatro familias',t:'Simbólica, aprendizaje, generativa y agéntica',b:'La simbólica explicita reglas; el aprendizaje obtiene patrones; la generativa produce contenido; la agéntica selecciona acciones.',e:'Un sistema puede combinar más de un enfoque.'},
  {k:'Agencia',t:'Un agente percibe y actúa para un objetivo',b:'Recibe información del entorno, selecciona una acción y afecta o informa ese entorno.',e:'Texto, formularios o APIs también pueden funcionar como sensores.'},
  {k:'Ciclo',t:'Percepción → razonamiento → acción',b:'La acción cambia el entorno o produce retroalimentación, creando un ciclo.',e:'Si solo hay una estimación, quizá existe un modelo, no un agente completo.'},
  {k:'Racionalidad',t:'Racional no significa infalible',b:'El agente elige la acción esperada más adecuada con la información y recursos disponibles.',e:'Puede ser racional abstenerse cuando falta información.'},
  {k:'Autonomía',t:'Más autonomía exige más controles',b:'La autonomía describe cuánto puede actuar sin intervención inmediata; no implica inteligencia superior.',e:'Acciones de alto impacto requieren autorización, límites y trazabilidad.'},
  {k:'Entorno',t:'El contexto cambia lo que el agente necesita',b:'Observabilidad, dinamismo, incertidumbre y presencia de otros agentes afectan el diseño.',e:'Un entorno parcial puede requerir memoria, inferencia o abstención.'},
  {k:'Especificación',t:'PEAS vuelve verificable la idea',b:'Desempeño, entorno, actuadores y sensores deben ser concretos y coherentes.',e:'Una buena medida incluye utilidad y daño posible, no solo rapidez.'}
];
let slideIndex=0;
function renderSlide(){const item=slides[slideIndex];$('#slideCard').innerHTML=`<p class="kicker">${item.k} · ${slideIndex+1}/${slides.length}</p><h3>${item.t}</h3><p>${item.b}</p><p class="example">${item.e}</p>`;$('#slideDots').innerHTML=slides.map((_,index)=>`<button aria-label="Ir a diapositiva ${index+1}" class="${index===slideIndex?'active':''}" data-index="${index}"></button>`).join('');$$('#slideDots button').forEach(button=>button.addEventListener('click',()=>{slideIndex=Number(button.dataset.index);renderSlide()}));$('#quickCheck').innerHTML=slideIndex===slides.length-1?'<h3>Comprobación rápida</h3><p>¿Dónde registrarías “enviar una alerta al tutor”?</p><button data-ok="0">Sensor</button><button data-ok="1">Actuador</button><button data-ok="0">Entorno</button>':'';$$('#quickCheck button').forEach(button=>button.addEventListener('click',()=>{button.classList.add(button.dataset.ok==='1'?'correct':'wrong');if(button.dataset.ok==='1'){state.slides=100;save()}}))}
$('#prevSlide').addEventListener('click',()=>{slideIndex=(slideIndex+slides.length-1)%slides.length;renderSlide()});$('#nextSlide').addEventListener('click',()=>{slideIndex=(slideIndex+1)%slides.length;renderSlide()});renderSlide();

const cases=[
  ['Hogar','Una cafetera se enciende todos los días a la hora programada.','Automatización','Ejecuta una regla temporal predefinida; no interpreta el contexto.'],
  ['Salud','Un componente recibe una radiografía y devuelve una probabilidad de anomalía, sin interfaz ni protocolo de uso.','Modelo','Transforma una entrada en una estimación; aún no constituye el sistema completo.'],
  ['Educación','Una plataforma reúne datos autorizados, estima necesidad de apoyo, aplica reglas de abstención y presenta el caso a un orientador.','Sistema inteligente','Integra percepción, modelo, política de decisión, interfaz y supervisión.'],
  ['Comercio','Una aplicación incorpora recomendador, pagos, atención, privacidad, soporte y métricas de experiencia.','Producto con IA','Incluye el sistema y toda la operación del servicio.'],
  ['Oficina','Una macro copia datos de una hoja a otra al presionar un botón.','Automatización','Ejecuta una secuencia definida sin inferencia contextual.'],
  ['Lenguaje','Un componente genera un resumen a partir de un texto, pero no verifica fuentes ni decide dónde publicarlo.','Modelo','Es un modelo generativo usado como componente.'],
  ['Movilidad','Un robot detecta obstáculos, actualiza su ruta y controla sus motores para llegar a un destino.','Sistema inteligente','Percibe, decide y actúa en un ciclo orientado a objetivos.'],
  ['Banca','Una app integra un modelo antifraude con políticas, alertas, atención humana, auditoría y comunicación al cliente.','Producto con IA','La solución incluye responsabilidades e interacción real con usuarios.']
];
const categories=['Automatización','Modelo','Sistema inteligente','Producto con IA'];let caseIndex=0,caseScore=0;
function renderCase(){const item=cases[caseIndex];$('#caseCount').textContent=`Caso ${caseIndex+1} de ${cases.length}`;$('#caseScore').textContent=`${caseScore} puntos`;$('#caseContext').textContent=item[0];$('#caseText').textContent=item[1];$('#caseFeedback').textContent='Selecciona una respuesta y explica mentalmente tu criterio.';$('#caseOptions').innerHTML=categories.map(category=>`<button>${category}</button>`).join('');$('#nextCase').disabled=true;$$('#caseOptions button').forEach(button=>button.addEventListener('click',()=>{if(!$('#nextCase').disabled)return;const ok=button.textContent===item[2];button.classList.add(ok?'correct':'wrong');if(ok)caseScore++;$$('#caseOptions button').forEach(option=>{option.disabled=true;if(option.textContent===item[2])option.classList.add('correct')});$('#caseFeedback').innerHTML=`<strong>${ok?'Correcto.':'Revisa tu clasificación.'}</strong> ${item[3]}`;$('#caseScore').textContent=`${caseScore} puntos`;$('#nextCase').disabled=false}))}
$('#nextCase').addEventListener('click',()=>{caseIndex++;if(caseIndex<cases.length)renderCase();else{$('#caseFeedback').innerHTML=`<strong>Reto completado: ${caseScore}/8.</strong> Revisa los casos incorrectos y explica qué componente faltaba.`;$('#nextCase').style.display='none';state.classifier=Math.max(state.classifier,Math.round(caseScore/8*100));save()}});renderCase();

const envCases=[
  {dimension:'Observabilidad',text:'Un robot ve solo el pasillo frente a su cámara; hay obstáculos detrás de una puerta.',options:['Completamente observable','Parcialmente observable'],ok:1,why:'No dispone de toda la información relevante. Puede necesitar memoria, exploración o abstención.'},
  {dimension:'Dinamismo',text:'Mientras un agente calcula una ruta, peatones y vehículos cambian de posición.',options:['Estático','Dinámico'],ok:1,why:'El entorno puede cambiar durante la deliberación; el agente debe actualizarse con rapidez.'},
  {dimension:'Incertidumbre',text:'La misma recomendación puede generar respuestas humanas distintas.',options:['Determinista','Estocástico'],ok:1,why:'Una acción no produce siempre el mismo resultado; conviene modelar incertidumbre y supervisar.'},
  {dimension:'Secuencia',text:'Aceptar una solicitud hoy limita las opciones y recursos disponibles mañana.',options:['Episódico','Secuencial'],ok:1,why:'Las decisiones actuales afectan estados y decisiones posteriores.'},
  {dimension:'Agentes',text:'Varios vehículos autónomos coordinan paso y compiten por espacio vial.',options:['Un solo agente','Multiagente'],ok:1,why:'Otras entidades toman decisiones y modifican el entorno.'},
  {dimension:'Conocimiento',text:'Las reglas, estados y resultados posibles están definidos antes de operar.',options:['Conocido','Desconocido'],ok:0,why:'El agente conoce el modelo operativo, aunque aún pueda existir incertidumbre sobre el estado.'}
];
let envIndex=0,envScore=0;
function renderEnv(){const item=envCases[envIndex];$('#envCount').textContent=`Caso ${envIndex+1} de ${envCases.length}`;$('#envScore').textContent=`${envScore} puntos`;$('#envDimension').textContent=item.dimension;$('#envText').textContent=item.text;$('#envFeedback').textContent='Selecciona la propiedad dominante.';$('#envOptions').innerHTML=item.options.map((option,index)=>`<button data-index="${index}">${option}</button>`).join('');$('#nextEnv').disabled=true;$$('#envOptions button').forEach(button=>button.addEventListener('click',()=>{if(!$('#nextEnv').disabled)return;const ok=Number(button.dataset.index)===item.ok;if(ok)envScore++;button.classList.add(ok?'correct':'wrong');$$('#envOptions button').forEach((option,index)=>{option.disabled=true;if(index===item.ok)option.classList.add('correct')});$('#envFeedback').innerHTML=`<strong>${ok?'Correcto.':'Revisa.'}</strong> ${item.why}`;$('#envScore').textContent=`${envScore} puntos`;$('#nextEnv').disabled=false}))}
$('#nextEnv').addEventListener('click',()=>{envIndex++;if(envIndex<envCases.length)renderEnv();else{$('#envFeedback').innerHTML=`<strong>Reto completado: ${envScore}/${envCases.length}.</strong> Explica ahora qué propiedad obliga a diseñar abstención.`;$('#nextEnv').style.display='none';state.environments=Math.round(envScore/envCases.length*100);save()}});renderEnv();

const agentCases=[
  ['Climatización','Si la temperatura supera el umbral, emite una recomendación inmediata. No conserva historia ni planifica.','Reactivo','Responde al estado actual mediante reglas directas.'],
  ['Logística','Compara varias rutas, anticipa costos futuros y elige un plan antes de actuar.','Deliberativo','Representa estados y evalúa consecuencias antes de seleccionar una acción.'],
  ['Robot móvil','Frena inmediatamente ante un obstáculo, pero planifica la ruta global para llegar a su destino.','Híbrido','Combina respuesta rápida con planificación.'],
  ['Chat con menú','Devuelve una respuesta fija para cada opción pulsada.','Reactivo','La interfaz conversacional no lo vuelve deliberativo.'],
  ['Agenda','Construye una secuencia de tareas que satisface restricciones de tiempo y recursos.','Deliberativo','Busca o planifica una secuencia orientada a una meta.'],
  ['Dron de inspección','Mantiene estabilidad con control inmediato y replanifica cuando detecta una zona bloqueada.','Híbrido','Separa control reactivo y replanteamiento deliberativo.']
];
const agentTypes=['Reactivo','Deliberativo','Híbrido'];let agentIndex=0,agentScore=0;
function renderAgent(){const item=agentCases[agentIndex];$('#agentCount').textContent=`Caso ${agentIndex+1} de ${agentCases.length}`;$('#agentScore').textContent=`${agentScore} puntos`;$('#agentContext').textContent=item[0];$('#agentText').textContent=item[1];$('#agentFeedback').textContent='Clasifica por el mecanismo de decisión.';$('#agentOptions').innerHTML=agentTypes.map(type=>`<button>${type}</button>`).join('');$('#nextAgent').disabled=true;$$('#agentOptions button').forEach(button=>button.addEventListener('click',()=>{if(!$('#nextAgent').disabled)return;const ok=button.textContent===item[2];if(ok)agentScore++;button.classList.add(ok?'correct':'wrong');$$('#agentOptions button').forEach(option=>{option.disabled=true;if(option.textContent===item[2])option.classList.add('correct')});$('#agentFeedback').innerHTML=`<strong>${ok?'Correcto.':'Revisa.'}</strong> ${item[3]}`;$('#agentScore').textContent=`${agentScore} puntos`;$('#nextAgent').disabled=false}))}
$('#nextAgent').addEventListener('click',()=>{agentIndex++;if(agentIndex<agentCases.length)renderAgent();else{$('#agentFeedback').innerHTML=`<strong>Reto completado: ${agentScore}/${agentCases.length}.</strong> Un diseño híbrido no es automáticamente mejor; debe justificarse por el entorno.`;$('#nextAgent').style.display='none';state.agentTypes=Math.round(agentScore/agentCases.length*100);save()}});renderAgent();

const pairs=[['Agente','Percibe y selecciona acciones'],['Entorno','Contexto donde opera'],['Sensor','Canal de información'],['Actuador','Medio para intervenir'],['Objetivo','Estado que busca favorecer'],['Desempeño','Criterio para evaluar'],['Percepción','Información interpretada'],['Acción','Respuesta que afecta o informa']];let deck=[],open=[],matched=0,moves=0;
function resetMemory(){deck=pairs.flatMap((pair,index)=>[{id:index,text:pair[0]},{id:index,text:pair[1]}]).sort(()=>Math.random()-.5);open=[];matched=0;moves=0;renderMemory()}
function renderMemory(){$('#memoryGrid').innerHTML=deck.map((card,index)=>`<button class="memory-card ${card.match?'matched':''}" data-index="${index}" aria-label="Tarjeta ${index+1}">${card.match?'✓ '+card.text:'?'}</button>`).join('');$('#moves').textContent=moves+' movimientos';$('#pairs').textContent=matched+' de 8 parejas';$$('.memory-card').forEach(button=>button.addEventListener('click',()=>flip(Number(button.dataset.index))))}
function flip(index){if(open.length===2||deck[index].match||open.includes(index))return;open.push(index);const button=$$('.memory-card')[index];button.textContent=deck[index].text;button.classList.add('revealed');if(open.length===2){moves++;const[a,b]=open;if(deck[a].id===deck[b].id){deck[a].match=deck[b].match=true;matched++;open=[];if(matched===8){state.memory=100;save()}setTimeout(renderMemory,350)}else setTimeout(()=>{open=[];renderMemory()},850)}}
$('#resetMemory').addEventListener('click',resetMemory);resetMemory();

const peasForm=$('#peasForm');peasForm.addEventListener('input',()=>{const data=Object.fromEntries(new FormData(peasForm));localStorage.setItem('si_u1_peas',JSON.stringify(data))});const oldPeas=JSON.parse(localStorage.getItem('si_u1_peas')||'{}');Object.entries(oldPeas).forEach(([key,value])=>{if(peasForm.elements[key])peasForm.elements[key].value=value});
function reviewPeas(){const data=Object.fromEntries(new FormData(peasForm));const checks=[['Problema y usuario delimitados',(data.user||'').length>35],['Decisión o tarea concreta',(data.task||'').length>25],['Desempeño incluye criterios verificables',(data.performance||'').length>35],['Entorno identifica actores y condiciones',(data.environment||'').length>35],['Actuadores describen acciones concretas',(data.actuators||'').length>25],['Sensores especifican información recibida',(data.sensors||'').length>25],['Límites, abstención y supervisión definidos',(data.limits||'').length>20&&(data.human||'').length>25]];$('#peasChecks').innerHTML=checks.map(([text,ok])=>`<li class="${ok?'pass':'warn'}">${ok?'✓':'△'} ${text}</li>`).join('');const count=checks.filter(([,ok])=>ok).length;$('#peasStatus').textContent=count===7?'La ficha supera la revisión básica de coherencia.':`Has cubierto ${count} de 7 comprobaciones.`;state.peas=Math.round(count/7*100);save();return data}
$('#reviewPeas').addEventListener('click',reviewPeas);$('#downloadPeas').addEventListener('click',()=>{const data=reviewPeas();const text=`FICHA PEAS · UNIDAD I\n\nAgente: ${data.name||''}\nUsuario y necesidad: ${data.user||''}\nDecisión/tarea: ${data.task||''}\n\nP · DESEMPEÑO\n${data.performance||''}\n\nE · ENTORNO\n${data.environment||''}\n\nA · ACTUADORES\n${data.actuators||''}\n\nS · SENSORES\n${data.sensors||''}\n\nFuera de alcance: ${data.limits||''}\nAbstención y supervisión humana: ${data.human||''}\n`;const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));link.download='Ficha_PEAS_Unidad_I.txt';link.click();URL.revokeObjectURL(link.href)});

const quiz=[
  ['¿Qué distingue a una automatización?',['Aprende siempre de datos','Ejecuta reglas o secuencias previstas','Tiene apariencia humana'],1,'Puede ser compleja y útil sin aprender.'],
  ['¿Qué es un modelo dentro de un sistema?',['Un componente que transforma entradas en salidas','El producto completo','La persona responsable'],0,'El modelo no incluye por sí solo operación ni supervisión.'],
  ['¿Cuál describe mejor a un agente?',['Almacena datos','Percibe y selecciona acciones orientadas a un objetivo','Solo genera texto'],1,'La agencia conecta percepción, decisión y acción.'],
  ['En PEAS, ¿dónde se define cómo evaluar el éxito?',['Entorno','Sensores','Desempeño'],2,'Las medidas deben cubrir utilidad y posibles daños.'],
  ['¿Cuál puede ser sensor de un asistente conversacional?',['Texto del usuario','Respuesta mostrada','Alerta enviada'],0,'Los sensores también pueden ser canales digitales.'],
  ['¿Cuál es actuador de un recomendador?',['Historial de navegación','Lista de recomendaciones mostrada','Base de datos'],1,'El actuador permite informar o afectar el entorno.'],
  ['Un entorno parcialmente observable significa que…',['No cambia nunca','El agente no conoce toda la información relevante','Solo admite una acción'],1,'La percepción incompleta genera incertidumbre.'],
  ['¿Qué delimita responsablemente a un agente?',['Darle acceso a todas las herramientas','Definir abstención y escalamiento humano','Ocultar los errores'],1,'Los límites previenen exceso de autonomía.'],
  ['Un agente que frena de inmediato y además planifica rutas es…',['Reactivo','Deliberativo','Híbrido'],2,'Combina control rápido con planificación.'],
  ['¿Por qué un chatbot con respuestas fijas no es necesariamente IA?',['Porque usa texto','Porque puede limitarse a reglas predeterminadas','Porque no tiene avatar'],1,'La interfaz no determina el mecanismo.'],
  ['¿Qué relación PEAS es coherente?',['Sensor: alerta; actuador: cámara','Sensor: cámara; actuador: alerta','Entorno: precisión; desempeño: pasillo'],1,'La cámara percibe y la alerta comunica una acción.'],
  ['¿Qué enseña la historia de la IA?',['Cada técnica nueva elimina las anteriores','Los sistemas actuales pueden combinar reglas, búsqueda y aprendizaje','La IA comenzó en 2022'],1,'Las tradiciones se combinan y se reutilizan en nuevos sistemas.']
];
$('#quizQuestions').innerHTML=quiz.map((item,index)=>`<fieldset class="question"><legend>${index+1}. ${item[0]}</legend>${item[1].map((answer,j)=>`<label><input type="radio" name="q${index}" value="${j}" required> ${answer}</label>`).join('')}<div id="qf${index}" class="note"></div></fieldset>`).join('');
$('#quizForm').addEventListener('submit',event=>{event.preventDefault();let score=0;const data=new FormData(event.target);quiz.forEach((item,index)=>{const answer=Number(data.get('q'+index));const ok=answer===item[2];if(ok)score++;$('#qf'+index).innerHTML=`<strong class="${ok?'pass':'warn'}">${ok?'Correcto.':'Revisa.'}</strong> ${item[3]}`});state.quiz=Math.round(score/quiz.length*100);save();$('#quizResult').classList.add('show');$('#quizResult').innerHTML=`<h3>Resultado: ${score}/${quiz.length}</h3><p>${score>=10?'Lograste el nivel esperado. Explica ahora los conceptos con tu propio caso.':'Revisa la retroalimentación y vuelve a intentarlo después de estudiar.'}</p>`;$('#quizResult').scrollIntoView({behavior:'smooth'})});
$('#printProgress').addEventListener('click',()=>print());$('#resetAll').addEventListener('click',()=>{if(confirm('¿Deseas borrar todo el progreso guardado en este dispositivo?')){localStorage.removeItem('si_u1');localStorage.removeItem('si_u1_peas');location.reload()}});

updateProgress();const initial=location.hash.slice(1);if($(`#${initial}.panel`))show(initial);
